name: Autologger
description: Automatic generation of the CHANGELOG.md file from Issues and the most recent Milestone.
author: "Inkling Interactive"
branding:
  icon: align-justify
  color: yellow
inputs:
  github-token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  github-repository:
    description: "The GitHub repository in the form user-or-org/project."
    required: true
runs:
  using: node12
  main: dist/main.js
