name: CI for TypeScript GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: Compile TypeScript
        run: |
          npm ci
          npx tsc
        env:
          CI: true
      - uses: autosuite/autocommit@master
        with:
          commit-message: "Automatically updated uncompiled TS w/ compiled JS"
      - uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - run: git pull --rebase || echo "You are pushing a tag, not a branch."
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: Compile TypeScript
        run: |
          npm ci
          npx tsc
        env:
          CI: true
      - name: Self-Test
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
      - uses: autosuite/autocommit@master
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  document:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2.0.0
      - run: git pull --rebase
      - uses: autosuite/autobadge@0.1.0
      - uses: autosuite/autoversion@master
      - uses: autosuite/autocommit@master
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  utility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: autosuite/automilestone@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
          prefix: rc-
