name: CI for TypeScript GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/setup-node@v1.1.2
      with:
        node-version: 12.x
    - name: Compile TypeScript
      run: |
        npm ci
        npx tsc
      env:
        CI: true
    - uses: autosuite/autocommit@master
      with:
        commit-message: "Automatically updated uncompiled TS w/ compiled JS"
    - uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Self-Test
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
  document:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: autosuite/autobadge@0.1.0
      - uses: autosuite/autoversion@0.1.0
      - uses: autosuite/autocommit@master
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  utility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: autosuite/automilestone@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
          prefix: rc-
